package com.contentsale.dataobject;

import java.util.Date;

public class CartDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.id
     *
     * @mbg.generated Fri Feb 22 11:05:08 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.item_id
     *
     * @mbg.generated Fri Feb 22 11:05:08 CST 2019
     */
    private Integer itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.item_title
     *
     * @mbg.generated Fri Feb 22 11:05:08 CST 2019
     */
    private String itemTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.user_id
     *
     * @mbg.generated Fri Feb 22 11:05:08 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.quantity
     *
     * @mbg.generated Fri Feb 22 11:05:08 CST 2019
     */
    private Integer quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.current_price
     *
     * @mbg.generated Fri Feb 22 11:05:08 CST 2019
     */
    private Double currentPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.create_time
     *
     * @mbg.generated Fri Feb 22 11:05:08 CST 2019
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.id
     *
     * @return the value of cart.id
     *
     * @mbg.generated Fri Feb 22 11:05:08 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.id
     *
     * @param id the value for cart.id
     *
     * @mbg.generated Fri Feb 22 11:05:08 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.item_id
     *
     * @return the value of cart.item_id
     *
     * @mbg.generated Fri Feb 22 11:05:08 CST 2019
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.item_id
     *
     * @param itemId the value for cart.item_id
     *
     * @mbg.generated Fri Feb 22 11:05:08 CST 2019
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.item_title
     *
     * @return the value of cart.item_title
     *
     * @mbg.generated Fri Feb 22 11:05:08 CST 2019
     */
    public String getItemTitle() {
        return itemTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.item_title
     *
     * @param itemTitle the value for cart.item_title
     *
     * @mbg.generated Fri Feb 22 11:05:08 CST 2019
     */
    public void setItemTitle(String itemTitle) {
        this.itemTitle = itemTitle == null ? null : itemTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.user_id
     *
     * @return the value of cart.user_id
     *
     * @mbg.generated Fri Feb 22 11:05:08 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.user_id
     *
     * @param userId the value for cart.user_id
     *
     * @mbg.generated Fri Feb 22 11:05:08 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.quantity
     *
     * @return the value of cart.quantity
     *
     * @mbg.generated Fri Feb 22 11:05:08 CST 2019
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.quantity
     *
     * @param quantity the value for cart.quantity
     *
     * @mbg.generated Fri Feb 22 11:05:08 CST 2019
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.current_price
     *
     * @return the value of cart.current_price
     *
     * @mbg.generated Fri Feb 22 11:05:08 CST 2019
     */
    public Double getCurrentPrice() {
        return currentPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.current_price
     *
     * @param currentPrice the value for cart.current_price
     *
     * @mbg.generated Fri Feb 22 11:05:08 CST 2019
     */
    public void setCurrentPrice(Double currentPrice) {
        this.currentPrice = currentPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.create_time
     *
     * @return the value of cart.create_time
     *
     * @mbg.generated Fri Feb 22 11:05:08 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.create_time
     *
     * @param createTime the value for cart.create_time
     *
     * @mbg.generated Fri Feb 22 11:05:08 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}