package com.contentsale.dataobject;

import java.util.Date;

public class FinanceDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance.id
     *
     * @mbg.generated Sun Jan 20 09:10:36 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance.item_id
     *
     * @mbg.generated Sun Jan 20 09:10:36 CST 2019
     */
    private Integer itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance.item_name
     *
     * @mbg.generated Sun Jan 20 09:10:36 CST 2019
     */
    private String itemName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance.item_img_url
     *
     * @mbg.generated Sun Jan 20 09:10:36 CST 2019
     */
    private String itemImgUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance.payment_time
     *
     * @mbg.generated Sun Jan 20 09:10:36 CST 2019
     */
    private Date paymentTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance.quantity
     *
     * @mbg.generated Sun Jan 20 09:10:36 CST 2019
     */
    private Integer quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance.each_price
     *
     * @mbg.generated Sun Jan 20 09:10:36 CST 2019
     */
    private Double eachPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance.total_price
     *
     * @mbg.generated Sun Jan 20 09:10:36 CST 2019
     */
    private Double totalPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance.buyer_id
     *
     * @mbg.generated Sun Jan 20 09:10:36 CST 2019
     */
    private Integer buyerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance.seller_id
     *
     * @mbg.generated Sun Jan 20 09:10:36 CST 2019
     */
    private Integer sellerId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance.id
     *
     * @return the value of finance.id
     *
     * @mbg.generated Sun Jan 20 09:10:36 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance.id
     *
     * @param id the value for finance.id
     *
     * @mbg.generated Sun Jan 20 09:10:36 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance.item_id
     *
     * @return the value of finance.item_id
     *
     * @mbg.generated Sun Jan 20 09:10:36 CST 2019
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance.item_id
     *
     * @param itemId the value for finance.item_id
     *
     * @mbg.generated Sun Jan 20 09:10:36 CST 2019
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance.item_name
     *
     * @return the value of finance.item_name
     *
     * @mbg.generated Sun Jan 20 09:10:36 CST 2019
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance.item_name
     *
     * @param itemName the value for finance.item_name
     *
     * @mbg.generated Sun Jan 20 09:10:36 CST 2019
     */
    public void setItemName(String itemName) {
        this.itemName = itemName == null ? null : itemName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance.item_img_url
     *
     * @return the value of finance.item_img_url
     *
     * @mbg.generated Sun Jan 20 09:10:36 CST 2019
     */
    public String getItemImgUrl() {
        return itemImgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance.item_img_url
     *
     * @param itemImgUrl the value for finance.item_img_url
     *
     * @mbg.generated Sun Jan 20 09:10:36 CST 2019
     */
    public void setItemImgUrl(String itemImgUrl) {
        this.itemImgUrl = itemImgUrl == null ? null : itemImgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance.payment_time
     *
     * @return the value of finance.payment_time
     *
     * @mbg.generated Sun Jan 20 09:10:36 CST 2019
     */
    public Date getPaymentTime() {
        return paymentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance.payment_time
     *
     * @param paymentTime the value for finance.payment_time
     *
     * @mbg.generated Sun Jan 20 09:10:36 CST 2019
     */
    public void setPaymentTime(Date paymentTime) {
        this.paymentTime = paymentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance.quantity
     *
     * @return the value of finance.quantity
     *
     * @mbg.generated Sun Jan 20 09:10:36 CST 2019
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance.quantity
     *
     * @param quantity the value for finance.quantity
     *
     * @mbg.generated Sun Jan 20 09:10:36 CST 2019
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance.each_price
     *
     * @return the value of finance.each_price
     *
     * @mbg.generated Sun Jan 20 09:10:36 CST 2019
     */
    public Double getEachPrice() {
        return eachPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance.each_price
     *
     * @param eachPrice the value for finance.each_price
     *
     * @mbg.generated Sun Jan 20 09:10:36 CST 2019
     */
    public void setEachPrice(Double eachPrice) {
        this.eachPrice = eachPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance.total_price
     *
     * @return the value of finance.total_price
     *
     * @mbg.generated Sun Jan 20 09:10:36 CST 2019
     */
    public Double getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance.total_price
     *
     * @param totalPrice the value for finance.total_price
     *
     * @mbg.generated Sun Jan 20 09:10:36 CST 2019
     */
    public void setTotalPrice(Double totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance.buyer_id
     *
     * @return the value of finance.buyer_id
     *
     * @mbg.generated Sun Jan 20 09:10:36 CST 2019
     */
    public Integer getBuyerId() {
        return buyerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance.buyer_id
     *
     * @param buyerId the value for finance.buyer_id
     *
     * @mbg.generated Sun Jan 20 09:10:36 CST 2019
     */
    public void setBuyerId(Integer buyerId) {
        this.buyerId = buyerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance.seller_id
     *
     * @return the value of finance.seller_id
     *
     * @mbg.generated Sun Jan 20 09:10:36 CST 2019
     */
    public Integer getSellerId() {
        return sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance.seller_id
     *
     * @param sellerId the value for finance.seller_id
     *
     * @mbg.generated Sun Jan 20 09:10:36 CST 2019
     */
    public void setSellerId(Integer sellerId) {
        this.sellerId = sellerId;
    }
}