package com.contentsale.dao;

import com.contentsale.dataobject.CartDO;

import java.util.List;

public interface CartDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbg.generated Sat Jan 19 13:17:49 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbg.generated Sat Jan 19 13:17:49 CST 2019
     */
    int insert(CartDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbg.generated Sat Jan 19 13:17:49 CST 2019
     */
    int insertSelective(CartDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbg.generated Sat Jan 19 13:17:49 CST 2019
     */
    CartDO selectByPrimaryKey(Integer id);

    CartDO selectByItemId(Integer itemId);

    List<CartDO> listItem(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbg.generated Sat Jan 19 13:17:49 CST 2019
     */
    int updateByPrimaryKeySelective(CartDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbg.generated Sat Jan 19 13:17:49 CST 2019
     */
    int updateByPrimaryKey(CartDO record);
}