package com.contentsale.dao;

import com.contentsale.dataobject.FinanceDO;

import java.util.List;

public interface FinanceDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table finance
     *
     * @mbg.generated Sun Jan 20 09:10:36 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table finance
     *
     * @mbg.generated Sun Jan 20 09:10:36 CST 2019
     */
    int insert(FinanceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table finance
     *
     * @mbg.generated Sun Jan 20 09:10:36 CST 2019
     */
    int insertSelective(FinanceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table finance
     *
     * @mbg.generated Sun Jan 20 09:10:36 CST 2019
     */
    FinanceDO selectByPrimaryKey(Integer id);

    List<FinanceDO> listItem(Integer buyerId);

    List<FinanceDO> listItemBySeller(Integer sellerId);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table finance
     *
     * @mbg.generated Sun Jan 20 09:10:36 CST 2019
     */
    int updateByPrimaryKeySelective(FinanceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table finance
     *
     * @mbg.generated Sun Jan 20 09:10:36 CST 2019
     */
    int updateByPrimaryKey(FinanceDO record);
}