package com.contentsale.dao;

import com.contentsale.dataobject.LoginTicketDO;

public interface LoginTicketDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_ticket
     *
     * @mbg.generated Mon Jan 14 16:51:30 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_ticket
     *
     * @mbg.generated Mon Jan 14 16:51:30 CST 2019
     */
    int insert(LoginTicketDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_ticket
     *
     * @mbg.generated Mon Jan 14 16:51:30 CST 2019
     */
    int insertSelective(LoginTicketDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_ticket
     *
     * @mbg.generated Mon Jan 14 16:51:30 CST 2019
     */
    LoginTicketDO selectByPrimaryKey(Integer id);

    LoginTicketDO selectByTicket(String ticket);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_ticket
     *
     * @mbg.generated Mon Jan 14 16:51:30 CST 2019
     */
    int updateByPrimaryKeySelective(LoginTicketDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_ticket
     *
     * @mbg.generated Mon Jan 14 16:51:30 CST 2019
     */
    int updateByPrimaryKey(LoginTicketDO record);
}