package com.contentsale.dao;

import com.contentsale.dataobject.OrderItemDO;

public interface OrderItemDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated Mon Jan 21 18:49:05 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated Mon Jan 21 18:49:05 CST 2019
     */
    int insert(OrderItemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated Mon Jan 21 18:49:05 CST 2019
     */
    int insertSelective(OrderItemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated Mon Jan 21 18:49:05 CST 2019
     */
    OrderItemDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated Mon Jan 21 18:49:05 CST 2019
     */
    int updateByPrimaryKeySelective(OrderItemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated Mon Jan 21 18:49:05 CST 2019
     */
    int updateByPrimaryKey(OrderItemDO record);
}